[build]
  base = "/"
  publish = "build/"
  command = "npm run build"
  functions = "functions/"

[dev]
  command = "npm run start"
  port = 8080
  targetPort = 3000
  publish = "dist"

[context.branch-deploy]
  command = "echo branch"
[context.branch-deploy.environment]
  NODE_ENV = "development"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''